# frozen_string_literal: true

require 'spec_helper'

RSpec.describe RubocopChallenger::PullRequest do
  let(:pull_request) do
    described_class.new('user_name', 'user_email', labels, dry_run)
  end

  let(:labels) { ['label-1', 'label-2'] }
  let(:dry_run) { false }

  let(:pr_creater) do
    instance_double(
      RubocopChallenger::Github::PrCreater, commit: nil, create_pr: nil
    )
  end

  before do
    allow(RubocopChallenger::Github::PrCreater)
      .to receive(:new).and_return(pr_creater)
    allow(pull_request).to receive(:timestamp).and_return('20181112212509')
  end

  describe '#commit!' do
    subject(:commit!) { pull_request.commit!('description') }

    it do
      commit!
      expect(pr_creater).to have_received(:commit).with('description')
    end
  end

  describe '#create_rubocop_challenge_pr!' do
    subject(:create_pull_request!) do
      pull_request.create_rubocop_challenge_pr!(rule, 'template_file_path')
    end

    let(:rule) do
      instance_double(RubocopChallenger::Rubocop::Rule, title: 'title')
    end
    let(:pr_template) do
      instance_double(RubocopChallenger::Github::PrTemplate, generate: 'body')
    end

    before do
      allow(RubocopChallenger::Github::PrTemplate)
        .to receive(:new).and_return(pr_template)
    end

    context 'when dry_run is true' do
      let(:dry_run) { true }

      it do
        create_pull_request!
        expect(RubocopChallenger::Github::PrTemplate)
          .to have_received(:new).with(rule, 'template_file_path')
      end

      it do
        create_pull_request!
        expect(pr_creater).not_to have_received(:create_pr)
      end
    end

    context 'when dry_run is false' do
      it do
        create_pull_request!
        expect(RubocopChallenger::Github::PrTemplate)
          .to have_received(:new).with(rule, 'template_file_path')
      end

      it do
        create_pull_request!
        expect(pr_creater).to have_received(:create_pr).with(
          title: 'title-20181112212509', body: 'body', labels: labels
        )
      end
    end
  end

  describe '#create_regenerate_todo_pr!' do
    subject(:create_pull_request!) do
      pull_request.create_regenerate_todo_pr!('0.64.0', '0.65.0')
    end

    context 'when dry_run is true' do
      let(:dry_run) { true }

      it do
        create_pull_request!
        expect(pr_creater).not_to have_received(:create_pr)
      end
    end

    context 'when dry_run is false' do
      let(:expected_options) do
        {
          title: 'Re-generate .rubocop_todo.yml with RuboCop v0.65.0',
          body: expected_pr_body,
          labels: labels
        }
      end

      let(:expected_pr_body) { <<~MARKDOWN }
        Re-generated the .rubocop_todo.yml because it was generated by old version RuboCop.

        * Using RuboCop version: `0.64.0` -> `0.65.0`

        Auto generated by [rubocop_challenger](https://github.com/ryz310/rubocop_challenger)
      MARKDOWN

      it do
        create_pull_request!
        expect(pr_creater).to have_received(:create_pr).with(expected_options)
      end
    end
  end
end
