# frozen_string_literal: true

module RubocopChallenger
  module Github
    # To generate Pull Request template as markdown
    class PrTemplate
      attr_reader :template_path

      def initialize(rule, template_path = nil)
        template_path = nil if template_path.empty?
        @template_path = template_path || default_template_path
        @template = File.read(template_path)
        @rule = rule
        @yardoc = Rubocop::Yardoc.new(title)
      end

      def generate
        <<~TEMPLATE
          #{ERB.new(template, nil, '-').result(binding)}
          Auto generated by [rubocop_challenger](https://github.com/ryz310/rubocop_challenger)
        TEMPLATE
      end

      private

      attr_reader :template, :rule, :yardoc

      def default_template_path
        File.expand_path('../../templates/default.md.erb', __dir__)
      end

      def title
        rule.title
      end

      def rubydoc_url
        rule.rubydoc_url
      end

      def description
        yardoc.description
      end

      def examples
        yardoc.examples
      end
    end
  end
end
