# frozen_string_literal: true

require 'spec_helper'

RSpec.describe RubocopChallenger::Github::PrTemplate do
  describe '#generate_pullrequest_markdown' do
    let(:pr_template) { described_class.new(rule) }

    let(:rule) { RubocopChallenger::Rubocop::Rule.new(<<~CONTENTS) }
      # Offense count: 2
      # Cop supports --auto-correct.
      Style/ExpandPathArguments:
        Exclude:
          - 'rubocop_challenger.gemspec'
    CONTENTS

    let(:expected_template) { <<~EXPECTED }
      # Rubocop challenge!

      [Style/ExpandPathArguments](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/ExpandPathArguments)

      ## Description

      > Use `expand_path(%<new_path>s%<new_default_dir>s)` instead of `expand_path(%<current_path>s, __FILE__)`.

      Auto generated by [rubocop_challenger](https://github.com/ryz310/rubocop_challenger)
    EXPECTED

    it 'returns PR template which includes rubydoc link and description' do
      expect(pr_template.generate_pullrequest_markdown).to eq expected_template
    end
  end
end
