# frozen_string_literal: true

require 'spec_helper'

RSpec.describe RubocopChallenger::Github::PrTemplate do
  describe '#generate_pullrequest_markdown' do
    let(:pr_template) { described_class.new(rule) }

    let(:rule) { RubocopChallenger::Rubocop::Rule.new(<<~CONTENTS) }
      # Offense count: 2
      # Cop supports --auto-correct.
      Style/ExpandPathArguments:
        Exclude:
          - 'rubocop_challenger.gemspec'
    CONTENTS

    let(:expected_template) { <<~EXPECTED }
      # Rubocop challenge!

      [Style/ExpandPathArguments](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/ExpandPathArguments)

      ## Description

      > This cop checks for use of the `File.expand_path` arguments.
      > Likewise, it also checks for the `Pathname.new` argument.
      > 
      > Contrastive bad case and good case are alternately shown in
      > the following examples.

      Auto generated by [rubocop_challenger](https://github.com/ryz310/rubocop_challenger)
    EXPECTED

    it 'returns PR template which includes rubydoc link and description' do
      expect(pr_template.generate_pullrequest_markdown).to eq expected_template
    end
  end
end
